wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.8
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693314495.421354
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 1
      - 7
      - 23
      4: 3.11.4
      5: 0.15.8
      8:
      - 5
    m:
    - 1: train/step
      6:
      - 3
    - 1: test/step
      6:
      - 3
    - 1: epoch
      6:
      - 3
    - 1: avg_train_loss_epoch
      5: 3
      6:
      - 1
      - 3
    - 1: avg_test_loss_epoch
      5: 3
      6:
      - 1
      - 3
    - 1: train/content_loss
      5: 1
      6:
      - 1
    - 1: train/style_loss
      5: 1
      6:
      - 1
    - 1: train/fid_loss
      5: 1
      6:
      - 1
    - 1: train/loss
      5: 1
      6:
      - 1
